// completely generated by gpt-5.4

'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import MediaMTXWebRTCPublisher from '@/lib/utils/mediamtx/webrtc';

const HLS_COMPATIBLE_VIDEO_CODECS = [
  ['h264', 'h264/90000'],
  ['vp9', 'vp9/90000'],
  ['av1', 'av1/90000'],
  ['h265', 'h265/90000'],
] as const;

const DISPLAY_MEDIA_OPTIONS: ScreenCaptureOptions = {
  video: true,
  audio: true,
  monitorTypeSurfaces: 'include',
  selfBrowserSurface: 'exclude',
  surfaceSwitching: 'include',
  systemAudio: 'include',
};

export function useScreensharePublisher({
  channelName,
  streamKey,
}: UseScreensharePublisherOptions) {
  const previewRef = useRef<HTMLVideoElement>(null);
  const captureStreamRef = useRef<MediaStream | null>(null);
  const captureCleanupRef = useRef<(() => void) | null>(null);
  const publisherRef = useRef<MediaMTXWebRTCPublisher | null>(null);
  const [publishState, setPublishState] = useState<PublishState>('idle');
  const [error, setError] = useState<string | null>(null);

  const setPreviewStream = useCallback((stream: MediaStream | null) => {
    if (previewRef.current) {
      previewRef.current.srcObject = stream;
    }
  }, []);

  const detachCaptureCleanup = useCallback(() => {
    captureCleanupRef.current?.();
    captureCleanupRef.current = null;
  }, []);

  const clearCaptureStream = useCallback(() => {
    detachCaptureCleanup();
    stopTracks(captureStreamRef.current);
    captureStreamRef.current = null;
    setPreviewStream(null);
  }, [detachCaptureCleanup, setPreviewStream]);

  const closePublisher = useCallback(() => {
    const publisher = publisherRef.current;

    publisherRef.current = null;
    publisher?.close();
  }, []);

  const disposeCurrentSession = useCallback(() => {
    closePublisher();
    clearCaptureStream();
  }, [clearCaptureStream, closePublisher]);

  const stopPublishing = useCallback(() => {
    disposeCurrentSession();
    setError(null);
    setPublishState('idle');
  }, [disposeCurrentSession]);

  const attachCaptureStopListener = useCallback(
    (stream: MediaStream) => {
      const [videoTrack] = stream.getVideoTracks();

      if (!videoTrack) {
        captureCleanupRef.current = null;
        return;
      }

      const handleEnded = () => {
        stopPublishing();
      };

      videoTrack.addEventListener('ended', handleEnded);
      captureCleanupRef.current = () => {
        videoTrack.removeEventListener('ended', handleEnded);
      };
    },
    [stopPublishing]
  );

  const commitCaptureStream = useCallback(
    (nextStream: MediaStream) => {
      const previousStream = captureStreamRef.current;

      detachCaptureCleanup();
      captureStreamRef.current = nextStream;
      setPreviewStream(nextStream);
      attachCaptureStopListener(nextStream);
      stopTracks(previousStream);
    },
    [attachCaptureStopListener, detachCaptureCleanup, setPreviewStream]
  );

  const startPublishing = useCallback(async () => {
    if (!channelName) {
      setError('Select a channel before starting your stream.');
      return;
    }

    if (!streamKey) {
      setError('Stream key unavailable for the selected channel.');
      return;
    }

    try {
      setError(null);
      setPublishState('connecting');

      const videoCodec = await getPreferredVideoCodec();
      const stream = await requestCaptureStream();

      commitCaptureStream(stream);

      const publisher = new MediaMTXWebRTCPublisher({
        url: getWhipUrl(channelName),
        stream,
        videoCodec,
        videoBitrate: 2000,
        audioCodec: 'opus',
        audioBitrate: 64,
        audioVoice: true,
        user: 'user',
        pass: streamKey,
        onConnected: () => {
          if (publisherRef.current !== publisher) {
            return;
          }

          setPublishState('live');
        },
        onError: (message) => {
          if (publisherRef.current !== publisher) {
            return;
          }

          setError(message);
          setPublishState('connecting');
        },
      });

      publisherRef.current = publisher;
    } catch (err) {
      disposeCurrentSession();
      setPublishState('idle');
      setError(getErrorMessage(err, 'Failed to start publishing'));
    }
  }, [channelName, commitCaptureStream, disposeCurrentSession, streamKey]);

  const changeSource = useCallback(async () => {
    const publisher = publisherRef.current;

    if (!publisher) {
      return;
    }

    let nextStream: MediaStream | null = null;

    try {
      setError(null);
      setPublishState('switching');

      nextStream = await requestCaptureStream();
      await publisher.replaceStream(nextStream);
      commitCaptureStream(nextStream);
      setPublishState('live');
    } catch (err) {
      stopTracks(nextStream);
      setPublishState(publisherRef.current ? 'live' : 'idle');
      setError(getErrorMessage(err, 'Failed to change screenshare source'));
    }
  }, [commitCaptureStream]);

  useEffect(() => {
    return () => {
      disposeCurrentSession();
    };
  }, [disposeCurrentSession]);

  return {
    changeSource,
    error,
    isLive: publishState === 'live',
    isSessionActive: publishState !== 'idle',
    isStarting: publishState === 'connecting',
    isSwitchingSource: publishState === 'switching',
    previewRef,
    startPublishing,
    stopPublishing,
  };
}

async function requestCaptureStream() {
  return navigator.mediaDevices.getDisplayMedia(DISPLAY_MEDIA_OPTIONS as DisplayMediaStreamOptions);
}

function getWhipUrl(channelName: string) {
  return `http://localhost:8889/${encodeURIComponent(channelName)}/whip`;
}

function stopTracks(stream: MediaStream | null) {
  stream?.getTracks().forEach((track) => track.stop());
}

function getErrorMessage(error: unknown, fallback: string) {
  return error instanceof Error ? error.message : fallback;
}

async function getPreferredVideoCodec(): Promise<string> {
  const tempPc = new RTCPeerConnection();

  try {
    tempPc.addTransceiver('video', { direction: 'sendonly' });

    const offer = await tempPc.createOffer();
    const sdp = offer.sdp?.toLowerCase() ?? '';

    for (const [codec, needle] of HLS_COMPATIBLE_VIDEO_CODECS) {
      if (sdp.includes(needle)) {
        return codec;
      }
    }
  } finally {
    tempPc.close();
  }

  throw new Error(
    'This browser does not expose an HLS-compatible WebRTC video codec. MediaMTX HLS supports AV1, VP9, H265, and H264, but not VP8.'
  );
}

type PublishState = 'idle' | 'connecting' | 'live' | 'switching';

type UseScreensharePublisherOptions = {
  channelName: string;
  streamKey?: string | null;
};

type ScreenCaptureOptions = DisplayMediaStreamOptions & {
  monitorTypeSurfaces?: 'include' | 'exclude';
  selfBrowserSurface?: 'include' | 'exclude';
  surfaceSwitching?: 'include' | 'exclude';
  systemAudio?: 'include' | 'exclude';
};
