paths:
  all:
    source: publisher

srt: yes
srtAddress: :8890

hls: yes
hlsVariant: lowLatency
hlsSegmentDuration: 2s
hlsPartDuration: 1s
hlsSegmentCount: 10

webrtc: yes
webrtcAddress: :8889
webrtcLocalUDPAddress: :8189
webrtcAdditionalHosts: []

authMethod: http
authHTTPAddress: https://hackclub.tv/api/mediamtx/publish
authHTTPFingerprint:

api: yes
apiAddress: :9997

metrics: yes
metricsAddress: :9998
