paths:
  all:
    source: publisher

srt: yes
srtAddress: :8890

hls: yes
hlsVariant: lowLatency
hlsSegmentDuration: 2s
hlsPartDuration: 500ms
hlsSegmentCount: 10

authMethod: http
authHTTPAddress: https://hackclub.tv/api/mediamtx/publish

api: yes
