paths:
  all:
    source: publisher

srt: yes
srtAddress: :8890

hls: yes
hlsAlwaysRemux: yes
hlsVariant: fmp4
hlsSegmentDuration: 2s
hlsSegmentCount: 15

webrtc: yes
webrtcAddress: :8889
webrtcLocalUDPAddress: :8189
webrtcAdditionalHosts: []

authMethod: http
authHTTPAddress: https://hackclub.tv/api/mediamtx/publish

api: yes
apiAddress: 0.0.0.0:9997
metrics: yes
metricsAddress: :9998
